static class Wordbank {
  static String[] bancoFrutas = {
    "melancia",
    "morango",
    "kiwi",
    "pera",
    "amora",
    "cereja",
    "uva",
    "mirtilo",
    "groselha",
    "figo",
    "laranja",
    "tangerina",
    "toranja",
    "caqui",
    "abacate",
    "abacaxi",
    "acerola",
    "ameixa",
    "banana",
    "cacau",
    "caju"
  };
  
  static String[] bancoAnimais = {
    "girafa",
    "elefante",
    "tigre",
    "crocodilo",
    "zebra",
    "macaco",
    "rinoceronte",
    "panda",
    "gorila",
    "tartaruga",
    "borboleta",
    "golfinho",
    "coruja",
    "pinguim",
    "canguru",
  };
  
  static String[] bancoPaises = {
    "brasil",
    "alemanha",
    "argentina",
    "espanha",
    "china",
    "portugal",
    "egito",
    "holanda",
    "noruega",
    "chile",
    "uruguai",
    "peru",
    "equador",
    "guatemala",
    "nepal",
    "filipinas",
    "cuba",
  };
  
  static String[] bancoObjetos = {
    "cadeira",
    "telefone",
    "ventilador",
    "espelho",
    "garfo",
    "panela",
    "escova",
    "lanterna",
    "chave",
    "mochila",
    "livro",
    "cama",
    "faca",
    "prato",
  };
}
